#!/bin/bash


E_ICON=' :'
C_ICON=' :'
STATE=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep state: | awk '{print $2}')

TIME_EMPTY=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep 'time to empty:' | awk '{print $4 $5}')

TIME_FULL=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep 'time to full:' | awk '{print $4 $5}')

get_time()
{
	if [[  "$STATE" == "charging" ]]; then
		echo "  $C_ICON $TIME_FULL  "
	else
		echo "  $E_ICON $TIME_EMPTY  "
	fi
}

get_time
